### ISSUE TITLE
galaxy version is not the same as the github one

### ISSUE THREAD

**Issue by ghost** [AMeng/spinnaker-ansible#9]
If you install the ansible galaxy version of this role
still does not come with the latest changes like configuration files for
front50-local.yml, echo-local.yml etc.
still the documentation here reflects those changes

**Comment by AMeng** [comment]
The Galaxy role has moved here: https://galaxy.ansible.com/AMeng/spinnaker-ansible/

For some reason Galaxy won't allow me to use the previous namespace anymore.

I've updated the REAME to reflect this.
